on: [push, pull_request]
name: "Continuous Integration \U0001F44C\U0001F440"
jobs:
  testSuite:
    name: Run Test Suite and Perl Critic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Test Docker Build and run Test Suite on it
      run: |
        docker build -t difegue/lanraragi:testing -f ./tools/build/docker/Dockerfile .
        echo "🎌 Running LRR Test Suite 🎌"
        docker run -t --entrypoint /bin/sh difegue/lanraragi:testing -c "apk add perl-utils perl-dev wget g++ make nodejs nodejs-npm && npm test"
    - name: Perl Critic
      uses: ./.github/action-critic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
